// ISO 3166-1 alpha-2 country list with Croatian + English names.
// 249 entries covering all officially-assigned codes.
module.exports = [
    ["AD", "Andora", "Andorra"],
    ["AE", "Ujedinjeni Arapski Emirati", "United Arab Emirates"],
    ["AF", "Afganistan", "Afghanistan"],
    ["AG", "Antigva i Barbuda", "Antigua and Barbuda"],
    ["AI", "Angvila", "Anguilla"],
    ["AL", "Albanija", "Albania"],
    ["AM", "Armenija", "Armenia"],
    ["AO", "Angola", "Angola"],
    ["AQ", "Antarktika", "Antarctica"],
    ["AR", "Argentina", "Argentina"],
    ["AS", "Američka Samoa", "American Samoa"],
    ["AT", "Austrija", "Austria"],
    ["AU", "Australija", "Australia"],
    ["AW", "Aruba", "Aruba"],
    ["AX", "Ålandski otoci", "Åland Islands"],
    ["AZ", "Azerbajdžan", "Azerbaijan"],
    ["BA", "Bosna i Hercegovina", "Bosnia and Herzegovina"],
    ["BB", "Barbados", "Barbados"],
    ["BD", "Bangladeš", "Bangladesh"],
    ["BE", "Belgija", "Belgium"],
    ["BF", "Burkina Faso", "Burkina Faso"],
    ["BG", "Bugarska", "Bulgaria"],
    ["BH", "Bahrein", "Bahrain"],
    ["BI", "Burundi", "Burundi"],
    ["BJ", "Benin", "Benin"],
    ["BL", "Saint Barthélemy", "Saint Barthélemy"],
    ["BM", "Bermudi", "Bermuda"],
    ["BN", "Brunej", "Brunei Darussalam"],
    ["BO", "Bolivija", "Bolivia"],
    ["BQ", "Bonaire, Sint Eustatius i Saba", "Bonaire, Sint Eustatius and Saba"],
    ["BR", "Brazil", "Brazil"],
    ["BS", "Bahami", "Bahamas"],
    ["BT", "Butan", "Bhutan"],
    ["BV", "Otok Bouvet", "Bouvet Island"],
    ["BW", "Bocvana", "Botswana"],
    ["BY", "Bjelorusija", "Belarus"],
    ["BZ", "Belize", "Belize"],
    ["CA", "Kanada", "Canada"],
    ["CC", "Kokosovi (Keelingovi) otoci", "Cocos (Keeling) Islands"],
    ["CD", "DR Kongo", "Congo, Democratic Republic of the"],
    ["CF", "Srednjoafrička Republika", "Central African Republic"],
    ["CG", "Kongo", "Congo"],
    ["CH", "Švicarska", "Switzerland"],
    ["CI", "Obala Bjelokosti", "Côte d'Ivoire"],
    ["CK", "Cookovi otoci", "Cook Islands"],
    ["CL", "Čile", "Chile"],
    ["CM", "Kamerun", "Cameroon"],
    ["CN", "Kina", "China"],
    ["CO", "Kolumbija", "Colombia"],
    ["CR", "Kostarika", "Costa Rica"],
    ["CU", "Kuba", "Cuba"],
    ["CV", "Zeleni rt", "Cabo Verde"],
    ["CW", "Curaçao", "Curaçao"],
    ["CX", "Božićni otok", "Christmas Island"],
    ["CY", "Cipar", "Cyprus"],
    ["CZ", "Češka", "Czechia"],
    ["DE", "Njemačka", "Germany"],
    ["DJ", "Džibuti", "Djibouti"],
    ["DK", "Danska", "Denmark"],
    ["DM", "Dominika", "Dominica"],
    ["DO", "Dominikanska Republika", "Dominican Republic"],
    ["DZ", "Alžir", "Algeria"],
    ["EC", "Ekvador", "Ecuador"],
    ["EE", "Estonija", "Estonia"],
    ["EG", "Egipat", "Egypt"],
    ["EH", "Zapadna Sahara", "Western Sahara"],
    ["ER", "Eritreja", "Eritrea"],
    ["ES", "Španjolska", "Spain"],
    ["ET", "Etiopija", "Ethiopia"],
    ["FI", "Finska", "Finland"],
    ["FJ", "Fidži", "Fiji"],
    ["FK", "Falklandski otoci", "Falkland Islands"],
    ["FM", "Mikronezija", "Micronesia"],
    ["FO", "Farski otoci", "Faroe Islands"],
    ["FR", "Francuska", "France"],
    ["GA", "Gabon", "Gabon"],
    ["GB", "Ujedinjeno Kraljevstvo", "United Kingdom"],
    ["GD", "Grenada", "Grenada"],
    ["GE", "Gruzija", "Georgia"],
    ["GF", "Francuska Gvajana", "French Guiana"],
    ["GG", "Guernsey", "Guernsey"],
    ["GH", "Gana", "Ghana"],
    ["GI", "Gibraltar", "Gibraltar"],
    ["GL", "Grenland", "Greenland"],
    ["GM", "Gambija", "Gambia"],
    ["GN", "Gvineja", "Guinea"],
    ["GP", "Gvadelupa", "Guadeloupe"],
    ["GQ", "Ekvatorijalna Gvineja", "Equatorial Guinea"],
    ["GR", "Grčka", "Greece"],
    ["GS", "Južna Georgija i Južni Sandwichevi otoci", "South Georgia and the South Sandwich Islands"],
    ["GT", "Gvatemala", "Guatemala"],
    ["GU", "Guam", "Guam"],
    ["GW", "Gvineja Bisau", "Guinea-Bissau"],
    ["GY", "Gvajana", "Guyana"],
    ["HK", "Hong Kong", "Hong Kong"],
    ["HM", "Otok Heard i otoci McDonald", "Heard Island and McDonald Islands"],
    ["HN", "Honduras", "Honduras"],
    ["HR", "Hrvatska", "Croatia"],
    ["HT", "Haiti", "Haiti"],
    ["HU", "Mađarska", "Hungary"],
    ["ID", "Indonezija", "Indonesia"],
    ["IE", "Irska", "Ireland"],
    ["IL", "Izrael", "Israel"],
    ["IM", "Otok Man", "Isle of Man"],
    ["IN", "Indija", "India"],
    ["IO", "Britanski indijskooceanski teritorij", "British Indian Ocean Territory"],
    ["IQ", "Irak", "Iraq"],
    ["IR", "Iran", "Iran"],
    ["IS", "Island", "Iceland"],
    ["IT", "Italija", "Italy"],
    ["JE", "Jersey", "Jersey"],
    ["JM", "Jamajka", "Jamaica"],
    ["JO", "Jordan", "Jordan"],
    ["JP", "Japan", "Japan"],
    ["KE", "Kenija", "Kenya"],
    ["KG", "Kirgistan", "Kyrgyzstan"],
    ["KH", "Kambodža", "Cambodia"],
    ["KI", "Kiribati", "Kiribati"],
    ["KM", "Komori", "Comoros"],
    ["KN", "Saint Kitts i Nevis", "Saint Kitts and Nevis"],
    ["KP", "Sjeverna Koreja", "Korea, Democratic People's Republic of"],
    ["KR", "Južna Koreja", "Korea, Republic of"],
    ["KW", "Kuvajt", "Kuwait"],
    ["KY", "Kajmanski otoci", "Cayman Islands"],
    ["KZ", "Kazahstan", "Kazakhstan"],
    ["LA", "Laos", "Lao People's Democratic Republic"],
    ["LB", "Libanon", "Lebanon"],
    ["LC", "Sveta Lucija", "Saint Lucia"],
    ["LI", "Lihtenštajn", "Liechtenstein"],
    ["LK", "Šri Lanka", "Sri Lanka"],
    ["LR", "Liberija", "Liberia"],
    ["LS", "Lesoto", "Lesotho"],
    ["LT", "Litva", "Lithuania"],
    ["LU", "Luksemburg", "Luxembourg"],
    ["LV", "Latvija", "Latvia"],
    ["LY", "Libija", "Libya"],
    ["MA", "Maroko", "Morocco"],
    ["MC", "Monako", "Monaco"],
    ["MD", "Moldavija", "Moldova"],
    ["ME", "Crna Gora", "Montenegro"],
    ["MF", "Saint Martin (francuski dio)", "Saint Martin (French part)"],
    ["MG", "Madagaskar", "Madagascar"],
    ["MH", "Maršalovi otoci", "Marshall Islands"],
    ["MK", "Sjeverna Makedonija", "North Macedonia"],
    ["ML", "Mali", "Mali"],
    ["MM", "Mijanmar", "Myanmar"],
    ["MN", "Mongolija", "Mongolia"],
    ["MO", "Makao", "Macao"],
    ["MP", "Sjeverni Marijanski otoci", "Northern Mariana Islands"],
    ["MQ", "Martinique", "Martinique"],
    ["MR", "Mauritanija", "Mauritania"],
    ["MS", "Montserrat", "Montserrat"],
    ["MT", "Malta", "Malta"],
    ["MU", "Mauricijus", "Mauritius"],
    ["MV", "Maldivi", "Maldives"],
    ["MW", "Malavi", "Malawi"],
    ["MX", "Meksiko", "Mexico"],
    ["MY", "Malezija", "Malaysia"],
    ["MZ", "Mozambik", "Mozambique"],
    ["NA", "Namibija", "Namibia"],
    ["NC", "Nova Kaledonija", "New Caledonia"],
    ["NE", "Niger", "Niger"],
    ["NF", "Otok Norfolk", "Norfolk Island"],
    ["NG", "Nigerija", "Nigeria"],
    ["NI", "Nikaragva", "Nicaragua"],
    ["NL", "Nizozemska", "Netherlands"],
    ["NO", "Norveška", "Norway"],
    ["NP", "Nepal", "Nepal"],
    ["NR", "Nauru", "Nauru"],
    ["NU", "Niue", "Niue"],
    ["NZ", "Novi Zeland", "New Zealand"],
    ["OM", "Oman", "Oman"],
    ["PA", "Panama", "Panama"],
    ["PE", "Peru", "Peru"],
    ["PF", "Francuska Polinezija", "French Polynesia"],
    ["PG", "Papua Nova Gvineja", "Papua New Guinea"],
    ["PH", "Filipini", "Philippines"],
    ["PK", "Pakistan", "Pakistan"],
    ["PL", "Poljska", "Poland"],
    ["PM", "Saint Pierre i Miquelon", "Saint Pierre and Miquelon"],
    ["PN", "Pitcairn", "Pitcairn"],
    ["PR", "Portoriko", "Puerto Rico"],
    ["PS", "Palestina", "Palestine, State of"],
    ["PT", "Portugal", "Portugal"],
    ["PW", "Palau", "Palau"],
    ["PY", "Paragvaj", "Paraguay"],
    ["QA", "Katar", "Qatar"],
    ["RE", "Reunion", "Réunion"],
    ["RO", "Rumunjska", "Romania"],
    ["RS", "Srbija", "Serbia"],
    ["RU", "Rusija", "Russian Federation"],
    ["RW", "Ruanda", "Rwanda"],
    ["SA", "Saudijska Arabija", "Saudi Arabia"],
    ["SB", "Salomonski otoci", "Solomon Islands"],
    ["SC", "Sejšeli", "Seychelles"],
    ["SD", "Sudan", "Sudan"],
    ["SE", "Švedska", "Sweden"],
    ["SG", "Singapur", "Singapore"],
    ["SH", "Sveta Helena", "Saint Helena, Ascension and Tristan da Cunha"],
    ["SI", "Slovenija", "Slovenia"],
    ["SJ", "Svalbard i Jan Mayen", "Svalbard and Jan Mayen"],
    ["SK", "Slovačka", "Slovakia"],
    ["SL", "Sijera Leone", "Sierra Leone"],
    ["SM", "San Marino", "San Marino"],
    ["SN", "Senegal", "Senegal"],
    ["SO", "Somalija", "Somalia"],
    ["SR", "Surinam", "Suriname"],
    ["SS", "Južni Sudan", "South Sudan"],
    ["ST", "Sveti Toma i Princip", "Sao Tome and Principe"],
    ["SV", "Salvador", "El Salvador"],
    ["SX", "Sint Maarten (nizozemski dio)", "Sint Maarten (Dutch part)"],
    ["SY", "Sirija", "Syrian Arab Republic"],
    ["SZ", "Esvatini", "Eswatini"],
    ["TC", "Otoci Turks i Caicos", "Turks and Caicos Islands"],
    ["TD", "Čad", "Chad"],
    ["TF", "Francuski južni teritoriji", "French Southern Territories"],
    ["TG", "Togo", "Togo"],
    ["TH", "Tajland", "Thailand"],
    ["TJ", "Tadžikistan", "Tajikistan"],
    ["TK", "Tokelau", "Tokelau"],
    ["TL", "Istočni Timor", "Timor-Leste"],
    ["TM", "Turkmenistan", "Turkmenistan"],
    ["TN", "Tunis", "Tunisia"],
    ["TO", "Tonga", "Tonga"],
    ["TR", "Turska", "Türkiye"],
    ["TT", "Trinidad i Tobago", "Trinidad and Tobago"],
    ["TV", "Tuvalu", "Tuvalu"],
    ["TW", "Tajvan", "Taiwan"],
    ["TZ", "Tanzanija", "Tanzania"],
    ["UA", "Ukrajina", "Ukraine"],
    ["UG", "Uganda", "Uganda"],
    ["UM", "Mali vanjski otoci SAD-a", "United States Minor Outlying Islands"],
    ["US", "Sjedinjene Američke Države", "United States of America"],
    ["UY", "Urugvaj", "Uruguay"],
    ["UZ", "Uzbekistan", "Uzbekistan"],
    ["VA", "Vatikan", "Holy See"],
    ["VC", "Sveti Vincent i Grenadini", "Saint Vincent and the Grenadines"],
    ["VE", "Venezuela", "Venezuela"],
    ["VG", "Britanski Djevičanski otoci", "Virgin Islands (British)"],
    ["VI", "Američki Djevičanski otoci", "Virgin Islands (U.S.)"],
    ["VN", "Vijetnam", "Viet Nam"],
    ["VU", "Vanuatu", "Vanuatu"],
    ["WF", "Wallis i Futuna", "Wallis and Futuna"],
    ["WS", "Samoa", "Samoa"],
    ["YE", "Jemen", "Yemen"],
    ["YT", "Mayotte", "Mayotte"],
    ["ZA", "Južnoafrička Republika", "South Africa"],
    ["ZM", "Zambija", "Zambia"],
    ["ZW", "Zimbabve", "Zimbabwe"],
];
